### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by AxVE** [citiususc/pastaspark#1]
Getting an ssl error on command "python setup.py develop --user"
=> urllib2.HTTPError: HTTP Error 403: SSL is required

I tried to direct download "http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
" and get the same error. I can download it from "https://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg"

**Comment by jmabuin** [comment]
Can you check if is it related with these?
https://stackoverflow.com/questions/46977498/urllib2-httperror-http-error-403-ssl-is-required-when-installing-nltk-2-0-5
https://mail.python.org/pipermail/distutils-sig/2017-October/031714.html

**Comment by AxVE** [comment]
From memory, it doesn't seem to be related.
I had overcome this problem, simply by replacing the link in ez_setup.py:

> $ git diff
> diff --git a/ez_setup.py b/ez_setup.py
> index 7aab12d..c0e0061 100755
> --- a/ez_setup.py
> +++ b/ez_setup.py
> @@ -15,7 +15,7 @@ This file can also be run as a script to install or upgrade setuptools.
>  """
>  import sys
>  DEFAULT_VERSION = "0.6c11"
> -DEFAULT_URL     = "http://pypi.python.org/packages/%s/s/setuptools/" % sys.version[:3]
> +DEFAULT_URL     = "https://pypi.python.org/packages/%s/s/setuptools/" % sys.version[:3]
>  
>  md5_data = {
>      'setuptools-0.6b1-py2.3.egg': '8822caf901250d848b996b7f25c6e6ca',

I had to do others things but I will try to finalize the install.
